/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 ./public/models/free_mclaren_p1_mso.glb 
Author: bohmerang (https://sketchfab.com/bohmerang)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/free-mclaren-p1-mso-c7687064e08c4be9a0af88e98bcf0a8e
Title: FREE - McLaren P1 MSO
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/free_mclaren_p1_mso.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.635, 0.328, 1.328]}>
        <group position={[0.199, -0.006, 0.005]}>
          <mesh geometry={nodes.Object_91.geometry} material={materials.Rims} />
          <mesh geometry={nodes.Object_92.geometry} material={materials.Details} />
        </group>
        <mesh geometry={nodes.Object_94.geometry} material={materials.tires} />
        <mesh geometry={nodes.Object_95.geometry} material={materials.tires} />
        <mesh geometry={nodes.Object_96.geometry} material={materials.tires2} />
      </group>
      <group position={[0.635, 0.328, -1.342]}>
        <group position={[0.173, -0.006, 0.005]}>
          <mesh geometry={nodes.Object_99.geometry} material={materials.Rims} />
          <mesh geometry={nodes.Object_100.geometry} material={materials.Details} />
        </group>
        <mesh geometry={nodes.Object_102.geometry} material={materials.tires} />
        <mesh geometry={nodes.Object_103.geometry} material={materials.tires} />
        <mesh geometry={nodes.Object_104.geometry} material={materials.tires2} />
      </group>
      <group position={[-0.793, 0.328, -1.342]}>
        <group position={[-0.173, -0.006, 0.005]}>
          <mesh geometry={nodes.Object_107.geometry} material={materials.Rims} />
          <mesh geometry={nodes.Object_108.geometry} material={materials.Details} />
        </group>
        <mesh geometry={nodes.Object_110.geometry} material={materials.tires} />
        <mesh geometry={nodes.Object_111.geometry} material={materials.tires} />
        <mesh geometry={nodes.Object_112.geometry} material={materials.tires2} />
      </group>
      <group position={[-0.793, 0.328, 1.328]}>
        <group position={[-0.199, -0.006, 0.005]}>
          <mesh geometry={nodes.Object_115.geometry} material={materials.Rims} />
          <mesh geometry={nodes.Object_116.geometry} material={materials.Details} />
        </group>
        <mesh geometry={nodes.Object_118.geometry} material={materials.tires} />
        <mesh geometry={nodes.Object_119.geometry} material={materials.tires} />
        <mesh geometry={nodes.Object_120.geometry} material={materials.tires2} />
      </group>
      <mesh geometry={nodes.Object_5.geometry} material={materials.BrakeDisk} />
      <mesh geometry={nodes.Object_7.geometry} material={materials.BrakeDisk} />
      <mesh geometry={nodes.Object_9.geometry} material={materials.Brakes} />
      <mesh geometry={nodes.Object_10.geometry} material={materials.Blue} />
      <mesh geometry={nodes.Object_12.geometry} material={materials.Carbon2} />
      <mesh geometry={nodes.Object_14.geometry} material={materials.Decals} />
      <mesh geometry={nodes.Object_16.geometry} material={materials.Details} />
      <mesh geometry={nodes.Object_17.geometry} material={materials.Blue} />
      <mesh geometry={nodes.Object_19.geometry} material={materials.Engine1} />
      <mesh geometry={nodes.Object_20.geometry} material={materials.Engine4} />
      <mesh geometry={nodes.Object_21.geometry} material={materials.Engine4} />
      <mesh geometry={nodes.Object_22.geometry} material={materials.Engine3} />
      <mesh geometry={nodes.Object_23.geometry} material={materials.Engine2} />
      <mesh geometry={nodes.Object_25.geometry} material={materials.Exhaust} />
      <mesh geometry={nodes.Object_27.geometry} material={materials.Glass} />
      <mesh geometry={nodes.Object_29.geometry} material={materials.Grid1} />
      <mesh geometry={nodes.Object_31.geometry} material={materials.Grid} />
      <mesh geometry={nodes.Object_33.geometry} material={materials.Grille} />
      <mesh geometry={nodes.Object_35.geometry} material={materials.Headlights} />
      <mesh geometry={nodes.Object_36.geometry} material={materials.HeadlightsEmissive} />
      <mesh geometry={nodes.Object_38.geometry} material={materials.Blue} />
      <mesh geometry={nodes.Object_39.geometry} material={materials.Blue} />
      <mesh geometry={nodes.Object_40.geometry} material={materials.Blue} />
      <mesh geometry={nodes.Object_41.geometry} material={materials.Interior} />
      <mesh geometry={nodes.Object_43.geometry} material={materials.Black} />
      <mesh geometry={nodes.Object_44.geometry} material={materials.Black} />
      <mesh geometry={nodes.Object_45.geometry} material={materials.Black} />
      <mesh geometry={nodes.Object_46.geometry} material={materials.Black} />
      <mesh geometry={nodes.Object_47.geometry} material={materials.Black} />
      <mesh geometry={nodes.Object_48.geometry} material={materials.Black} />
      <mesh geometry={nodes.Object_50.geometry} material={materials.Carbon1} />
      <mesh geometry={nodes.Object_51.geometry} material={materials.Carbon1} />
      <mesh geometry={nodes.Object_52.geometry} material={materials.Carbon1} />
      <mesh geometry={nodes.Object_53.geometry} material={materials.Blue} />
      <mesh geometry={nodes.Object_55.geometry} material={materials.WhitePaintjob} />
      <mesh geometry={nodes.Object_56.geometry} material={materials.Carbon} />
      <mesh geometry={nodes.Object_57.geometry} material={materials.Blue} />
      <mesh geometry={nodes.Object_59.geometry} material={materials.Plastics} />
      <mesh geometry={nodes.Object_61.geometry} material={materials.Mechanicals} />
      <mesh geometry={nodes.Object_63.geometry} material={materials.Mirror} />
      <mesh geometry={nodes.Object_65.geometry} material={materials.Pipes} />
      <mesh geometry={nodes.Object_67.geometry} material={materials.Plate} />
      <mesh geometry={nodes.Object_69.geometry} material={materials.Black} />
      <mesh geometry={nodes.Object_71.geometry} material={materials.Glossy} />
      <mesh geometry={nodes.Object_73.geometry} material={materials.SafetyBelt} />
      <mesh geometry={nodes.Object_75.geometry} material={materials.GridSoundSytem} />
      <mesh geometry={nodes.Object_77.geometry} material={materials.Carbon} />
      <mesh geometry={nodes.Object_79.geometry} material={materials.Blue} />
      <mesh geometry={nodes.Object_81.geometry} material={materials.Black} />
      <mesh geometry={nodes.Object_83.geometry} material={materials.Glossy} />
      <mesh geometry={nodes.Object_85.geometry} material={materials.Stitchwork} />
      <mesh geometry={nodes.Object_87.geometry} material={materials.TaillightsEmissive} />
      <mesh geometry={nodes.Object_88.geometry} material={materials.TaillightsReflective} />
    </group>
  )
}

useGLTF.preload('/free_mclaren_p1_mso.glb')
